### ISSUE TITLE
插件无法下载，错误500

### ISSUE THREAD

**Issue by zcc0077** [Sunbelife/Snowboard-IconPack-for-Smartisan-OS#18]
孙总你好，https://apt.sunbelife.com/ 里的插件都报错500错误，无法下载了，如方便的话可否提供锤子主题deb包发我，谢谢 452607371@qq.com

**Comment by Sunbelife** [comment]
可以，在这里：https://ibeta.cowtransfer.com/s/fe3830f763554e
